export interface BankMasrCheckoutConfigAuthentication {
  /**
   * The transactionId you used for the Initiate Authentication operation.
   * @validation min: 1, max: 40
   */
  transactionId?: string;
  /**
   * Information about payer authentication using 3-D Secure authentication.
   *
   * Only provide these fields if you authenticated the payer using a different 3-D Secure service provider. If you authenticated the payer using the gateway, then provide authentication.transactionId instead.
   *
   * Parameters in this group apply to both 3-D Secure authentication version 1 and 3-D Secure Authentication version 2.
   *
   * Depending on the 3-D Secure authentication version applicable you will also need additional parameters:
   * - 3-D Secure authentication version 1: see the authentication.3ds1 parameter group.
   * - 3-D Secure authentication version 2: see the authentication.3ds2 parameter group.
   */
  '3ds'?: {
    /**
     * A unique identifier for the 3-D Secure authentication transaction.
     * For 3DS version 1, this field corresponds to the XID. The XID is an identifier generated by the gateway on behalf of the merchant.
     *
     * For 3DS version 2, this field corresponds to the identifier assigned by the scheme directory server.
     *
     * This identifier should be used in subsequent operation requests unaltered, An XID submitted in this field must be in base64 format.
     * @validation min: 1, max: 50
     */
    transactionId?: string;
    /**
     * The base64 encoded value generated by the issuer.
     * The authentication token Included in subsequent transaction request messages and used by the card scheme to verify that the authentication occurred and the values provided are valid. The token should be used unaltered. For 3DS version 1, this field corresponds to the Cardholder Authentication Verification Value (CAVV) for Visa, the Accountholder Authentication Value (AAV) for MasterCard and JCB, or the American Express Verification Value (AEVV) for American Express.
     *
     * For 3DS version 2, this field corresponds to the Authentication Value.
     * @validation Data is Base64 encoded, allowable lengths 28 or 32
     */
    authenticationToken?: string;
    /**
     * Indicates the security level of the transaction.
     *
     * This is the Electronic Commerce Indicator (ECI) value provided by the issuer's Access Control Server (ACS) to indicate the results of the attempt to authenticate the payer.
     * @validation Data may consist of the characters 0-9, a-z, A-Z, allowed lengths 1 or 2
     */
    acsEci?: string;
  };
  /**
   * Information about payer authentication using 3-D Secure authentication version 1.
   *
   * Only provide these fields if you authenticated the payer using a different 3-D Secure service provider. If you authenticated the payer using the gateway, then provide authentication.transactionId instead.
   */
  '3ds1'?: {
    /**
     * Indicates the result of payer authentication with the issuer.
     *
     * This is the value returned in the transaction status field of the Payer Authentication Response (PARes) message from the card Issuer's Access Control Server (ACS). For example, Y, N, A, or U. Refer to the relevant documentation for Mastercard SecureCode™, Verified by Visa™, JCB J/Secure™, American Express SafeKey™, or Diners Club ProtectBuy™.
     * @validation Data may consist of the characters a-z, A-Z, allowed length 1
     */
    paResStatus?: string;
    /**
     * Indicates whether or not payer authentication is available for the card number you provided.
     *
     * This is for experts only - most users should use the response.gatewayRecommendation field.
     *
     * This is the value returned in the 'enrolled' field of the Verify Enrollment Response (VERes) message from the card scheme's Directory Server. For example, Y, N, or U. Refer to the relevant documentation for Mastercard SecureCode™, Verified by Visa™, JCB J/Secure™, American Express SafeKey™, or Diners Club ProtectBuy™.
     * @validation Data may consist of the characters a-z, A-Z, allowed length 1
     */
    veResEnrolled?: string;
  };
}
